package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

const serviceLabel = "org.activitywatch.herdr"
const serviceUnit = "aw-watcher-herdr.service"
const serviceMarker = "Generated by aw-watcher-herdr service install."

type serviceLayout struct {
	platform, config, logDir, domain string
}

func servicePaths(platform, home, configHome string, uid int) (serviceLayout, error) {
	s := serviceLayout{platform: platform}
	switch platform {
	case "darwin":
		s.config = filepath.Join(home, "Library", "LaunchAgents", serviceLabel+".plist")
		s.logDir = filepath.Join(home, "Library", "Logs", "aw-watcher-herdr")
		s.domain = fmt.Sprintf("gui/%d", uid)
	case "linux":
		if configHome == "" {
			configHome = filepath.Join(home, ".config")
		}
		if !filepath.IsAbs(configHome) {
			return s, fmt.Errorf("XDG_CONFIG_HOME must be absolute for service installation")
		}
		s.config = filepath.Join(configHome, "systemd", "user", serviceUnit)
	default:
		return s, fmt.Errorf("service management supports macOS and Linux; current platform: %s", platform)
	}
	return s, nil
}

func serviceArguments(executable string, c Config) []string {
	return []string{executable,
		"--herdr", c.Herdr, "--socket", c.Socket, "--aw-url", c.AW, "--hostname", c.Host,
		"--selection-interval", c.SelectionInterval.String(), "--heartbeat-interval", c.HeartbeatInterval.String(),
		"--pulsetime", c.PulseTime.String(), "--retry-interval", c.RetryInterval.String(), "--timeout", c.Timeout.String(),
	}
}

func xmlText(s string) (string, error) {
	var b bytes.Buffer
	if err := xml.EscapeText(&b, []byte(s)); err != nil {
		return "", err
	}
	return b.String(), nil
}

// systemd expands % specifiers in both settings and command lines, but expands
// $ variables only in ExecStart. Quotes prevent whitespace splitting.
func unitQuote(s string, command bool) string {
	s = strings.ReplaceAll(s, "%", "%%")
	if command {
		s = strings.ReplaceAll(s, "$", "$$")
	}
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`, "\t", `\t`).Replace(s) + `"`
}

func renderService(s serviceLayout, args []string, env map[string]string, restartSeconds float64) ([]byte, error) {
	for _, value := range args {
		if strings.ContainsRune(value, 0) {
			return nil, fmt.Errorf("service argument contains NUL")
		}
	}
	keys := make([]string, 0, len(env))
	for k, v := range env {
		if strings.ContainsRune(v, 0) {
			return nil, fmt.Errorf("environment variable %s contains NUL", k)
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	if s.platform == "darwin" {
		b.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- " + serviceMarker + " -->\n<plist version=\"1.0\"><dict>\n")
		b.WriteString("<key>Label</key><string>" + serviceLabel + "</string>\n<key>ProgramArguments</key><array>\n")
		writeString := func(value string) error {
			escaped, err := xmlText(value)
			if err != nil {
				return err
			}
			b.WriteString("<string>" + escaped + "</string>\n")
			return nil
		}
		for _, arg := range args {
			if err := writeString(arg); err != nil {
				return nil, err
			}
		}
		b.WriteString("</array>\n<key>EnvironmentVariables</key><dict>\n")
		for _, k := range keys {
			b.WriteString("<key>" + k + "</key>")
			if err := writeString(env[k]); err != nil {
				return nil, err
			}
		}
		b.WriteString("</dict>\n<key>RunAtLoad</key><true/>\n<key>KeepAlive</key><true/>\n")
		b.WriteString("<key>StandardOutPath</key>")
		if err := writeString(filepath.Join(s.logDir, "stdout.log")); err != nil {
			return nil, err
		}
		b.WriteString("<key>StandardErrorPath</key>")
		if err := writeString(filepath.Join(s.logDir, "stderr.log")); err != nil {
			return nil, err
		}
		b.WriteString("</dict></plist>\n")
	} else {
		b.WriteString("# " + serviceMarker + "\n[Unit]\nDescription=Herdr activity watcher for ActivityWatch\n\n[Service]\nType=exec\nExecStart=")
		for i, arg := range args {
			if i > 0 {
				b.WriteByte(' ')
			}
			b.WriteString(unitQuote(arg, true))
		}
		b.WriteByte('\n')
		for _, k := range keys {
			b.WriteString("Environment=" + unitQuote(k+"="+env[k], false) + "\n")
		}
		// Reuse the configured reconnect delay, rather than invent another interval.
		fmt.Fprintf(&b, "Restart=always\nRestartSec=%gs\nStandardOutput=journal\nStandardError=journal\n\n[Install]\nWantedBy=default.target\n", restartSeconds)
	}
	return []byte(b.String()), nil
}
